### ISSUE TITLE
Awesome Font "icons" on front page not working properly

### ISSUE THREAD

**Issue by dobbsbp** [SenjinDarashiva/hugo-uno#25]
My problem is kind of odd.  When my page loads, it seems like the font doesnt work correctly and in place of the awesome font icons, it shows squares as seen in the screen capture below.  BUT!  If i click my name/title, the page reloads and then the fonts work properly.

Im also wondering if Chrome is the issue as it seem to work ok in ~~Internet Explorer~~ Edge.
Live website is at [www.bendobbs.com](url) but be aware that it is a work in progress and not all is working just yet.

![fontissue](https://cloud.githubusercontent.com/assets/13375701/14482114/5093b09c-0163-11e6-9177-a09e61230a23.jpg)

**Comment by SenjinDarashiva** [comment]
It seems to be a CORS issue, if you try to load your page withouth the www the fonts seems to be working. However if you try http://www.bendobbs.com/#blog the icons will be missing again. One solution would probably be to force redirect either to www. or withouth www. and then set the page url in the hugo config accordingly.

Otherwise you could possibly try this https://davidwalsh.name/cdn-fonts depending on how you host your page.

**Comment by dobbsbp** [comment]
Ah!!!! that would make some sense.  I'll see about making some changes to make it work.

**Comment by dobbsbp** [comment]
Resolved.  I created a .htaccess file via my website host's website and included the following code:

RewriteEngine on
RewriteCond %{HTTP_HOST} ^bendobbs\.com$ [NC]
RewriteRule ^(.*)$ http://www.bendobbs.com/$1 [R=301,L]

Source: 
http://www.thesitewizard.com/apache/redirect-domain-www-subdomain.shtml

I found your link to be a little confusing on how it works.  This one seemed to do the trick.

Thanks for your help and hard work!
